 <?xml version="1.0" standalone="yes">
 <!--Example of internal DTD in XML Document -->
 <!DOCTYPE employee [
 <!ELEMENT employee (emp+)>
 <!ELEMENT emp (no,name,salary)>
 <!ATTLIST emp i ID #REQUIRED>
 <!ELEMENT no (#PCDATA) >
 <!ELEMENT name (#PCDATA)>
 <!ELEMENT salary (#PCDATA)>
 ]>

<employee>
    <emp i="1">
        <no>13612</no>  
        <name>Abdullah</name>  
        <department>Computer Science</department> 
        <salary>750</salary> 
        
    </emp>  
</employee>
